### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by DennisLfromGA** [reynhout/cbiddb#1]
I'm just curious as to how you source this?
It's very handy, thanx.

-DennisL

**Comment by reynhout** [comment]
The source is a data file used by the Google script for making ChromeOS recovery images: https://dl.google.com/dl/edgedl/chromeos/recovery/linux_recovery.sh

I turned the output into JSON so it'd be easier to see the diffs. I parse the data file every few days.

**Comment by DennisLfromGA** [comment]
Thanx @reynhout, I just recently finished a script to download and parse that data file myself.
Here's the resultant gsheet - [Recovery-IDs](https://goo.gl/GdaPM8)
I could have sworn that previous versions of the `recovery.conf` file included the 'hwid' but it seems to be missing in the latest ones.

**Comment by reynhout** [comment]
I've only been tracking it for six months or so, but if I had to guess... They probably started out with "hwid" but decided it wasn't flexible enough to match all models precisely (e.g. the white label MIGHTY models), so they added "hwidmatch" to determine specific product names. All models within a class seem to use the same recovery image, but maybe they use the "name" or "desc" fields for display purposes somewhere?

I don't need that much specificity, just the simple base hwid to track new models...so I parse that out and take a SHA of the regex to watch for changes. I use the base hwid to keep ../chrx and https://wiki.galliumos.org/Hardware_Compatibility updated.

I'm not sure if it's useful to anyone else, but I put it up on github for convenient visual diffs. :)

**Comment by DennisLfromGA** [comment]
Yup, thanx for the explanation.

I'll be getting a Dell Chromebook 13 (i5/8GB/32GB) any day now and plan to use 'chrx' to install _something_ on it. I haven't quite decided exactly what I want, maybe Gallium OS, but not sure.

I may even go with one of HugeGreenBug's Linux Mint distros, I have it running on my HP Chromebook 14 and my wife _loves_ it.

**Comment by DennisLfromGA** [comment]
I'm what they call a [Rising Star](https://goo.gl/ogqPYo) (not yet a TC) in the Chromebook Central forums and we import your json file into a gsheet for our reference - it's very handy.

**Comment by reynhout** [comment]
Awesome, I'm glad it's useful. As I mentioned, I do endeavour to keep it current, generally within a few days. So it should be pretty reliable going forward.

Ah, the LULU. Nice machine. You should be happy with any customized Linux distro there. Mint is nice, but GalliumOS is definitely worth a spin and is likely to be getting the majority of attention from HGB's customization work going forward.
